config/routes.rb
Testapp::Application.routes.draw do
  resources :articles

  get "welcome/index"
  post "motivation/webhook/:id" => "Articles#webhook"

   root :to => 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :text, :title
end

app/models/book.rb
class Book < ActiveRecord::Base
  # attr_accessible :title, :body
  name varchar(255)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def new
    
    end
    def create
         @article = Article.new(params[:article])
 
         @article.save
         redirect_to @article
    end

    def show
        @article = Article.find(params[:id])
    end

    def webhook
        @article = Article.find(params[:id])
        puts params[:data][:status]
        i = @article.title.to_i
        if (params[:type] == 'deal') && (params[:data][:status] == 'won')
            @article.title = i+1
        end
        @article.text = 'Get out there and make some deals!' if @article.title.to_i<1
        @article.text = 'Nice start, keep it up!' if @article.title.to_i>0
        @article.text = 'WOW! look at you go!' if @article.title.to_i>5
        @article.text = 'Just keep doing what your doing, its clearly working' if @article.title.to_i>10
        @article.save
        render :text => 'Successful', :status => :ok
    end

    private
        def article_params
            params.require(:article).permit(:title, :text)
        end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Number of Deals Won:</strong>
  <%= @article.title %>
</p>
  
<p>
  <%= @article.text%>
</p> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>